Repository mosn/envoy-go-extension, pull requests merged in 2022-11, with the labels that each got.

#20 chore: upgrade envoy to newest tag, and use patch to export symbols
  Makefile
  WORKSPACE
  envoy.bazelrc
  export-syms.patch
  export-syms.txt
  src/envoy/http/golang/golang_filter.cc
Labels: cla:yes, size/M

#21 bugfix: should not save the DsoInstance when failed to load so file.
  src/envoy/common/dso/dso.cc
  src/envoy/common/dso/dso.h
Labels: question, cla:yes, size/M

#23 chore: build with clang 11
  .bazelversion
  Makefile
  README.md
  envoy.bazelrc
  src/envoy/http/golang/cgo.cc
  src/envoy/http/golang/golang_filter.h
  test/http/golang/golang_filter_test.cc
  test/http/golang/golang_integration_test.cc
Labels: cla:yes, size/M

#24 feature: implemented the StreamInfo().GetRouteName() API.
  pkg/http/api.h
  pkg/http/api/capi.go
  pkg/http/api/filter.go
  pkg/http/capi.go
  pkg/http/filter.go
  src/envoy/http/golang/cgo.cc
  src/envoy/http/golang/golang_filter.cc
  src/envoy/http/golang/golang_filter.h
  test/http/golang/golang_integration_test.cc
  test/http/golang/test_data/basic/filter.go
  test/http/golang/test_data/basic/go.mod
  test/http/golang/test_data/passthrough/go.mod
Labels: cla:yes, size/L

#26 feature: support append and prepend buffer in http filter
  pkg/http/api.h
  pkg/http/api/capi.go
  pkg/http/api/type.go
  pkg/http/capi.go
  pkg/http/filter.go
  src/envoy/common/dso/api.h
  src/envoy/common/dso/libgolang.h
  src/envoy/http/golang/cgo.cc
  src/envoy/http/golang/golang_filter.cc
  src/envoy/http/golang/golang_filter.h
  test/http/golang/golang_integration_test.cc
  test/http/golang/test_data/basic/filter.go
Labels: cla:yes, size/L

#25 ci: add test in github action.
  .github/workflows/manual.yaml
  .github/workflows/reviewdog.yml
  ci/envoy_build_sha.sh
  ci/run_envoy_docker.sh
  pkg/http/BUILD
  pkg/http/api/type.go
  pkg/http/capi.go
Labels: cla:yes, size/L

#27 add open source clause
  main.go
  pkg/http/api/capi.go
  pkg/http/api/filter.go
  pkg/http/api/type.go
  pkg/http/capi.go
  pkg/http/filtermanager.go
  pkg/http/moe.go
  pkg/http/passthrough.go
  pkg/utils/string.go
  samples/async-sleep/filter.go
  samples/async/filter.go
  samples/buffered/filter.go
Labels: cla:yes, size/L

#28 fix map race
  pkg/http/config.go
  pkg/http/filtermanager.go
  pkg/http/moe.go
Labels: bug, cla:yes, size/L

#30 bazel: upgrade bazelversion to 6.0.0r1
  .bazelversion
  WORKSPACE
  bazel/platform_mappings
  envoy.bazelrc
Labels: cla:yes, size/L

#31 feature: support route config specified from typed_per_filter_config
  Makefile
  WORKSPACE
  bazel/dso.bzl
  pkg/http/api/BUILD
  pkg/http/api/filter.go
  pkg/http/filtermanager.go
  pkg/http/moe.go
  scripts/check-test-data-compile.sh
  src/envoy/common/dso/dso.cc
  src/envoy/common/dso/dso.h
  src/envoy/common/dso/libgolang.h
  src/envoy/http/golang/BUILD
  src/envoy/http/golang/golang_filter.cc
  src/envoy/http/golang/golang_filter.h
  test/common/dso/test_data/simple.go
  test/http/golang/BUILD
  test/http/golang/golang_integration_test.cc
  test/http/golang/test_data/routeconfig/BUILD
  test/http/golang/test_data/routeconfig/filter.go
  test/http/golang/test_data/routeconfig/go.mod
Labels: cla:yes, size/L

#32 ci: enable goimports to check import style
  .github/workflows/reviewdog.yml
Labels: cla:yes, size/XS

#33 refactor: introduce a ProcessorState class to simpfy state code.
  src/envoy/http/golang/BUILD
  src/envoy/http/golang/golang_filter.cc
  src/envoy/http/golang/golang_filter.h
  src/envoy/http/golang/processor_state.cc
  src/envoy/http/golang/processor_state.h
Labels: cla:yes, size/XXL

#34 refactor: move the end_stream flag to ProcessorState.
  src/envoy/http/golang/golang_filter.cc
  src/envoy/http/golang/golang_filter.h
  src/envoy/http/golang/processor_state.h
Labels: cla:yes, size/M

#36 change: new MOSN API depends on envoy go basic API.
  main.go
  pkg/http/api/type.go
  pkg/http/filtermanager.go
  pkg/http/mosn/buffer.go
  pkg/http/mosn/filtermanager.go
  pkg/http/mosn/stream.go
  pkg/http/type.go
Labels: cla:yes, size/L

#37 change: used buffer list instead of a single buffer for the processing buffer data.
  src/envoy/http/golang/golang_filter.cc
  src/envoy/http/golang/golang_filter.h
  src/envoy/http/golang/processor_state.cc
  src/envoy/http/golang/processor_state.h
  test/http/golang/golang_integration_test.cc
Labels: cla:yes, size/L

#38 change: MOSN Buffer API depends on DataBufferBase API.
  pkg/http/api/type.go
  pkg/http/mosn/stream.go
  pkg/http/mosn/type.go
  pkg/http/type.go
Labels: cla:yes, size/L

#39 change: used the new API for the test filters.
  .github/workflows/reviewdog.yml
  Makefile
  test/http/golang/test_data/basic/filter.go
  test/http/golang/test_data/routeconfig/filter.go
Labels: cla:yes, size/M

#40 test: make test passed again.
  .github/workflows/reviewdog.yml
  pkg/http/BUILD
  pkg/http/config.go
  test/http/golang/golang_integration_test.cc
Labels: cla:yes, size/S

#41 move all //export into export.go
  .gitignore
  Makefile
  bazel/dso.bzl
  export.go
  mosn.json
  pkg/api/BUILD
  pkg/api/api.h
  pkg/api/capi.go
  pkg/api/filter.go
  pkg/api/type.go
  pkg/http/BUILD
  pkg/http/buffered/BUILD
  pkg/http/buffered/api.go
  pkg/http/buffered/filtermanager.go
  pkg/http/capi.go
  pkg/http/config.go
  pkg/http/filter.go
  pkg/http/filtermanager.go
  pkg/http/moe.go
  pkg/http/mosn/filtermanager.go
  pkg/http/mosn/stream.go
  pkg/http/mosn/type.go
  pkg/http/passthrough.go
  pkg/http/type.go
  samples/async-sleep/filter.go
  samples/async/filter.go
  samples/buffered/filter.go
  src/envoy/common/dso/libgolang.h
  test/http/golang/test_data/basic/filter.go
  test/http/golang/test_data/routeconfig/filter.go
Labels: cla:yes, size/L

#42 add some implementations for streamFilterHandler
  pkg/http/mosn/stream.go
Labels: cla:yes, size/M

#44 fix typo
  export.go
  pkg/http/config.go
  src/envoy/common/dso/dso.cc
  src/envoy/common/dso/dso.h
  src/envoy/common/dso/libgolang.h
  src/envoy/http/golang/golang_filter.cc
  test/common/dso/test_data/simple.go
Labels: bug, cla:yes, size/M

#46 revert: move //export back to moe.go and config.go.
  Makefile
  export.go
  pkg/http/BUILD
  pkg/http/api.h
  pkg/http/capi.go
  pkg/http/config.go
  pkg/http/moe.go
  src/envoy/common/dso/libgolang.h
Labels: cla:yes, size/L

#45 feature: added more APIs for RequestHeaderMap & ResponseHeaderMap interface.
  pkg/api/type.go
  pkg/http/moe.go
  pkg/http/type.go
Labels: cla:yes, size/L
