Repository mosn/envoy-go-extension, pull requests merged in 2022-12, with the labels that each got.

#49 feat: add GetRaw for ResponseHeaderMap
  pkg/api/type.go
  pkg/http/type.go
Labels: cla:yes, size/S

#50 feat: add headerMapImpl.Values to return multiple headers
  pkg/api/capi.go
  pkg/api/type.go
  pkg/http/capi.go
  pkg/http/type.go
  test/http/golang/golang_integration_test.cc
  test/http/golang/test_data/basic/filter.go
Labels: cla:yes, size/L

#53 added recover in defer to catch panic.
  pkg/api/filter.go
  pkg/http/buffered/filtermanager.go
  pkg/http/capi.go
  pkg/http/filter.go
  pkg/http/moe.go
  pkg/http/type.go
  test/http/golang/golang_integration_test.cc
  test/http/golang/test_data/badapicall/BUILD
  test/http/golang/test_data/badapicall/filter.go
  test/http/golang/test_data/badapicall/go.mod
  test/http/golang/test_data/basic/filter.go
Labels: cla:yes, size/L

#59 chore: use info level log for normal behavior
  src/envoy/http/golang/golang_filter.cc
Labels: cla:yes, size/XS

#61 manipulate dynamic metadata
  pkg/api/capi.go
  pkg/api/filter.go
  pkg/http/BUILD
  pkg/http/api.h
  pkg/http/capi.go
  pkg/http/filter.go
  pkg/http/moe.go
  pkg/http/sema.go
  src/envoy/common/dso/api.h
  src/envoy/common/dso/dso.cc
  src/envoy/common/dso/dso.h
  src/envoy/common/dso/libgolang.h
  src/envoy/http/golang/cgo.cc
  src/envoy/http/golang/golang_filter.cc
  src/envoy/http/golang/golang_filter.h
  src/envoy/http/golang/processor_state.h
  test/common/dso/test_data/simple.go
  test/http/golang/golang_integration_test.cc
  test/http/golang/test_data/basic/filter.go
Labels: cla:yes, size/L

#62 change: move the waitgroup sema into httpRequest struct.
  pkg/api/BUILD
  pkg/api/capi.go
  pkg/http/BUILD
  pkg/http/api.h
  pkg/http/capi.go
  pkg/http/filter.go
  pkg/http/moe.go
  pkg/http/sema.go
  src/envoy/common/dso/api.h
  src/envoy/common/dso/dso.cc
  src/envoy/common/dso/dso.h
  src/envoy/common/dso/libgolang.h
  src/envoy/http/golang/cgo.cc
  src/envoy/http/golang/golang_filter.cc
  src/envoy/http/golang/golang_filter.h
  test/common/dso/test_data/simple.go
Labels: cla:yes, size/L

#63 change: use r *httpRequest instead of r *unsafe.Pointer in the methods of the HttpCAPI interface.
  pkg/http/capi.go
  pkg/http/filter.go
  pkg/http/type.go
Labels: cla:yes, size/L

#64 should add lock for the httpRequestInternel.strValue to avoid concurrency writing.
  pkg/http/capi.go
  pkg/http/filter.go
Labels: cla:yes, size/S
